#!/usr/bin/env bash

# Resets the bluetooth adapter and spawns a bluetooth interface script

_term() {
    echo "Caught SIGTERM Signal."
    kill -2 $child
}
trap _term SIGTERM

echo -n "Resetting bluetooth... "
bash    resetbluetooth
sleep 1
echo "done."

echo "Executing ble.py..."
echo

echo "python ble.py $@"
python ble.py $@

echo 
echo -n "Resetting bluetooth... "
bash    resetbluetooth
sleep 1
echo "done."
